/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp book.xml -i book.h -a bookAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef BOOKADAPTOR_H
#define BOOKADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "book.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface atech.e99.mpl
 */
class MplAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "atech.e99.mpl")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"atech.e99.mpl\">\n"
"    <property access=\"read\" type=\"i\" name=\"person_removed\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"person_updated\"/>\n"
"    <signal name=\"personAdded\">\n"
"      <arg direction=\"out\" type=\"siss\" name=\"msg\"/>\n"
"      <annotation value=\"Person\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"personRemoved\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"name\"/>\n"
"    </signal>\n"
"    <signal name=\"messageSent\">\n"
"      <arg direction=\"out\" type=\"siss\" name=\"msg\"/>\n"
"      <!-- to support also Qt < 5.6.3 & 5.7.0, use instead \"org.qtproject.QtDBus.QtTypeName.In0\" -->\n"
"      <annotation value=\"message\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <method name=\"ipersonRemoved\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"ipersonUpdated\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"addPerson\">\n"
"      <arg direction=\"in\" type=\"siss\" name=\"person\"/>\n"
"      <annotation value=\"Person\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MplAdaptor(QObject *parent);
    virtual ~MplAdaptor();

public: // PROPERTIES
    Q_PROPERTY(int person_removed READ person_removed)
    int person_removed() const;

    Q_PROPERTY(int person_updated READ person_updated)
    int person_updated() const;

public Q_SLOTS: // METHODS
    void addPerson(const Person &person);
    int ipersonRemoved();
    int ipersonUpdated();
Q_SIGNALS: // SIGNALS
    void messageSent(const message &msg);
    void personAdded(const Person &person);
    void personRemoved(const QString &name);
};

#endif
