/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp book.xml -i book.h -a bookAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "bookAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MplAdaptor
 */

MplAdaptor::MplAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MplAdaptor::~MplAdaptor()
{
    // destructor
}

int MplAdaptor::person_removed() const
{
    // get the value of property person_removed
    return qvariant_cast< int >(parent()->property("person_removed"));
}

int MplAdaptor::person_updated() const
{
    // get the value of property person_updated
    return qvariant_cast< int >(parent()->property("person_updated"));
}

void MplAdaptor::addPerson(const Person &person)
{
    // handle method call atech.e99.mpl.addPerson
    QMetaObject::invokeMethod(parent(), "addPerson", Q_ARG(Person, person));
}

int MplAdaptor::ipersonRemoved()
{
    // handle method call atech.e99.mpl.ipersonRemoved
    int out0;
    QMetaObject::invokeMethod(parent(), "ipersonRemoved", Q_RETURN_ARG(int, out0));
    return out0;
}

int MplAdaptor::ipersonUpdated()
{
    // handle method call atech.e99.mpl.ipersonUpdated
    int out0;
    QMetaObject::invokeMethod(parent(), "ipersonUpdated", Q_RETURN_ARG(int, out0));
    return out0;
}

