/*
 * Generated by gdbus-codegen 2.55.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "comm_dbus.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface atech.e99.mpl.shm
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:commAtechE99MplShm
 * @title: commAtechE99MplShm
 * @short_description: Generated C code for the atech.e99.mpl.shm D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-atech-e99-mpl-shm.top_of_page">atech.e99.mpl.shm</link> D-Bus interface in C.
 */

/* ---- Introspection data for atech.e99.mpl.shm ---- */

static const _ExtendedGDBusArgInfo _comm_atech_e99_mpl_shm_method_info_add_member_IN_ARG_memberdetails1 =
{
  {
    -1,
    (gchar *) "memberdetails1",
    (gchar *) "a(ss)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _comm_atech_e99_mpl_shm_method_info_add_member_IN_ARG_memberdetails2 =
{
  {
    -1,
    (gchar *) "memberdetails2",
    (gchar *) "iy",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _comm_atech_e99_mpl_shm_method_info_add_member_IN_ARG_pointers[] =
{
  &_comm_atech_e99_mpl_shm_method_info_add_member_IN_ARG_memberdetails1,
  &_comm_atech_e99_mpl_shm_method_info_add_member_IN_ARG_memberdetails2,
  NULL
};

static const _ExtendedGDBusArgInfo _comm_atech_e99_mpl_shm_method_info_add_member_OUT_ARG_response =
{
  {
    -1,
    (gchar *) "response",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _comm_atech_e99_mpl_shm_method_info_add_member_OUT_ARG_pointers[] =
{
  &_comm_atech_e99_mpl_shm_method_info_add_member_OUT_ARG_response,
  NULL
};

static const _ExtendedGDBusMethodInfo _comm_atech_e99_mpl_shm_method_info_add_member =
{
  {
    -1,
    (gchar *) "AddMember",
    (GDBusArgInfo **) &_comm_atech_e99_mpl_shm_method_info_add_member_IN_ARG_pointers,
    (GDBusArgInfo **) &_comm_atech_e99_mpl_shm_method_info_add_member_OUT_ARG_pointers,
    NULL
  },
  "handle-add-member",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _comm_atech_e99_mpl_shm_method_info_pointers[] =
{
  &_comm_atech_e99_mpl_shm_method_info_add_member,
  NULL
};

static const _ExtendedGDBusArgInfo _comm_atech_e99_mpl_shm_signal_info_changes_notification_ARG_member_id =
{
  {
    -1,
    (gchar *) "member_id",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _comm_atech_e99_mpl_shm_signal_info_changes_notification_ARG_change =
{
  {
    -1,
    (gchar *) "change",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _comm_atech_e99_mpl_shm_signal_info_changes_notification_ARG_pointers[] =
{
  &_comm_atech_e99_mpl_shm_signal_info_changes_notification_ARG_member_id,
  &_comm_atech_e99_mpl_shm_signal_info_changes_notification_ARG_change,
  NULL
};

static const _ExtendedGDBusSignalInfo _comm_atech_e99_mpl_shm_signal_info_changes_notification =
{
  {
    -1,
    (gchar *) "ChangesNotification",
    (GDBusArgInfo **) &_comm_atech_e99_mpl_shm_signal_info_changes_notification_ARG_pointers,
    NULL
  },
  "changes-notification"
};

static const _ExtendedGDBusSignalInfo * const _comm_atech_e99_mpl_shm_signal_info_pointers[] =
{
  &_comm_atech_e99_mpl_shm_signal_info_changes_notification,
  NULL
};

static const _ExtendedGDBusPropertyInfo _comm_atech_e99_mpl_shm_property_info_verbose =
{
  {
    -1,
    (gchar *) "Verbose",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "verbose",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _comm_atech_e99_mpl_shm_property_info_pointers[] =
{
  &_comm_atech_e99_mpl_shm_property_info_verbose,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _comm_atech_e99_mpl_shm_interface_info =
{
  {
    -1,
    (gchar *) "atech.e99.mpl.shm",
    (GDBusMethodInfo **) &_comm_atech_e99_mpl_shm_method_info_pointers,
    (GDBusSignalInfo **) &_comm_atech_e99_mpl_shm_signal_info_pointers,
    (GDBusPropertyInfo **) &_comm_atech_e99_mpl_shm_property_info_pointers,
    NULL
  },
  "atech-e99-mpl-shm",
};


/**
 * comm_atech_e99_mpl_shm_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-atech-e99-mpl-shm.top_of_page">atech.e99.mpl.shm</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
comm_atech_e99_mpl_shm_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_comm_atech_e99_mpl_shm_interface_info.parent_struct;
}

/**
 * comm_atech_e99_mpl_shm_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #commAtechE99MplShm interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
comm_atech_e99_mpl_shm_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "verbose");
  return property_id_begin - 1;
}



/**
 * commAtechE99MplShm:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-atech-e99-mpl-shm.top_of_page">atech.e99.mpl.shm</link>.
 */

/**
 * commAtechE99MplShmIface:
 * @parent_iface: The parent interface.
 * @handle_add_member: Handler for the #commAtechE99MplShm::handle-add-member signal.
 * @get_verbose: Getter for the #commAtechE99MplShm:verbose property.
 * @changes_notification: Handler for the #commAtechE99MplShm::changes-notification signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-atech-e99-mpl-shm.top_of_page">atech.e99.mpl.shm</link>.
 */

typedef commAtechE99MplShmIface commAtechE99MplShmInterface;
G_DEFINE_INTERFACE (commAtechE99MplShm, comm_atech_e99_mpl_shm, G_TYPE_OBJECT)

static void
comm_atech_e99_mpl_shm_default_init (commAtechE99MplShmIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * commAtechE99MplShm::handle-add-member:
   * @object: A #commAtechE99MplShm.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_memberdetails1: Argument passed by remote caller.
   * @arg_memberdetails2: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-atech-e99-mpl-shm.AddMember">AddMember()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call comm_atech_e99_mpl_shm_complete_add_member() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add-member",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (commAtechE99MplShmIface, handle_add_member),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT, G_TYPE_VARIANT);

  /* GObject signals for received D-Bus signals: */
  /**
   * commAtechE99MplShm::changes-notification:
   * @object: A #commAtechE99MplShm.
   * @arg_member_id: Argument.
   * @arg_change: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-atech-e99-mpl-shm.ChangesNotification">"ChangesNotification"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("changes-notification",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (commAtechE99MplShmIface, changes_notification),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_INT, G_TYPE_UINT);

  /* GObject properties for D-Bus properties: */
  /**
   * commAtechE99MplShm:verbose:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-atech-e99-mpl-shm.Verbose">"Verbose"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("verbose", "Verbose", "Verbose", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * comm_atech_e99_mpl_shm_get_verbose: (skip)
 * @object: A #commAtechE99MplShm.
 *
 * Gets the value of the <link linkend="gdbus-property-atech-e99-mpl-shm.Verbose">"Verbose"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
comm_atech_e99_mpl_shm_get_verbose (commAtechE99MplShm *object)
{
  return COMM_ATECH_E99_MPL_SHM_GET_IFACE (object)->get_verbose (object);
}

/**
 * comm_atech_e99_mpl_shm_set_verbose: (skip)
 * @object: A #commAtechE99MplShm.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-atech-e99-mpl-shm.Verbose">"Verbose"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
comm_atech_e99_mpl_shm_set_verbose (commAtechE99MplShm *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "verbose", value, NULL);
}

/**
 * comm_atech_e99_mpl_shm_emit_changes_notification:
 * @object: A #commAtechE99MplShm.
 * @arg_member_id: Argument to pass with the signal.
 * @arg_change: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-atech-e99-mpl-shm.ChangesNotification">"ChangesNotification"</link> D-Bus signal.
 */
void
comm_atech_e99_mpl_shm_emit_changes_notification (
    commAtechE99MplShm *object,
    gint arg_member_id,
    guint arg_change)
{
  g_signal_emit_by_name (object, "changes-notification", arg_member_id, arg_change);
}

/**
 * comm_atech_e99_mpl_shm_call_add_member:
 * @proxy: A #commAtechE99MplShmProxy.
 * @arg_memberdetails1: Argument to pass with the method invocation.
 * @arg_memberdetails2: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-atech-e99-mpl-shm.AddMember">AddMember()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call comm_atech_e99_mpl_shm_call_add_member_finish() to get the result of the operation.
 *
 * See comm_atech_e99_mpl_shm_call_add_member_sync() for the synchronous, blocking version of this method.
 */
void
comm_atech_e99_mpl_shm_call_add_member (
    commAtechE99MplShm *proxy,
    GVariant *arg_memberdetails1,
    GVariant *arg_memberdetails2,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "AddMember",
    g_variant_new ("(@a(ss)@iy)",
                   arg_memberdetails1,
                   arg_memberdetails2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * comm_atech_e99_mpl_shm_call_add_member_finish:
 * @proxy: A #commAtechE99MplShmProxy.
 * @out_response: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to comm_atech_e99_mpl_shm_call_add_member().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with comm_atech_e99_mpl_shm_call_add_member().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
comm_atech_e99_mpl_shm_call_add_member_finish (
    commAtechE99MplShm *proxy,
    gint *out_response,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_response);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * comm_atech_e99_mpl_shm_call_add_member_sync:
 * @proxy: A #commAtechE99MplShmProxy.
 * @arg_memberdetails1: Argument to pass with the method invocation.
 * @arg_memberdetails2: Argument to pass with the method invocation.
 * @out_response: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-atech-e99-mpl-shm.AddMember">AddMember()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See comm_atech_e99_mpl_shm_call_add_member() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
comm_atech_e99_mpl_shm_call_add_member_sync (
    commAtechE99MplShm *proxy,
    GVariant *arg_memberdetails1,
    GVariant *arg_memberdetails2,
    gint *out_response,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "AddMember",
    g_variant_new ("(@a(ss)@iy)",
                   arg_memberdetails1,
                   arg_memberdetails2),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_response);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * comm_atech_e99_mpl_shm_complete_add_member:
 * @object: A #commAtechE99MplShm.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @response: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-atech-e99-mpl-shm.AddMember">AddMember()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
comm_atech_e99_mpl_shm_complete_add_member (
    commAtechE99MplShm *object,
    GDBusMethodInvocation *invocation,
    gint response)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   response));
}

/* ------------------------------------------------------------------------ */

/**
 * commAtechE99MplShmProxy:
 *
 * The #commAtechE99MplShmProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * commAtechE99MplShmProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #commAtechE99MplShmProxy.
 */

struct _commAtechE99MplShmProxyPrivate
{
  GData *qdata;
};

static void comm_atech_e99_mpl_shm_proxy_iface_init (commAtechE99MplShmIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (commAtechE99MplShmProxy, comm_atech_e99_mpl_shm_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (commAtechE99MplShmProxy)
                         G_IMPLEMENT_INTERFACE (COMM_TYPE_ATECH_E99_MPL_SHM, comm_atech_e99_mpl_shm_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (commAtechE99MplShmProxy, comm_atech_e99_mpl_shm_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (COMM_TYPE_ATECH_E99_MPL_SHM, comm_atech_e99_mpl_shm_proxy_iface_init))

#endif
static void
comm_atech_e99_mpl_shm_proxy_finalize (GObject *object)
{
  commAtechE99MplShmProxy *proxy = COMM_ATECH_E99_MPL_SHM_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (comm_atech_e99_mpl_shm_proxy_parent_class)->finalize (object);
}

static void
comm_atech_e99_mpl_shm_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _comm_atech_e99_mpl_shm_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
comm_atech_e99_mpl_shm_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface atech.e99.mpl.shm: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
comm_atech_e99_mpl_shm_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _comm_atech_e99_mpl_shm_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "atech.e99.mpl.shm", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) comm_atech_e99_mpl_shm_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
comm_atech_e99_mpl_shm_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_comm_atech_e99_mpl_shm_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], COMM_TYPE_ATECH_E99_MPL_SHM);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, COMM_TYPE_ATECH_E99_MPL_SHM);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
comm_atech_e99_mpl_shm_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  commAtechE99MplShmProxy *proxy = COMM_ATECH_E99_MPL_SHM_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_comm_atech_e99_mpl_shm_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_comm_atech_e99_mpl_shm_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gboolean 
comm_atech_e99_mpl_shm_proxy_get_verbose (commAtechE99MplShm *object)
{
  commAtechE99MplShmProxy *proxy = COMM_ATECH_E99_MPL_SHM_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Verbose");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
comm_atech_e99_mpl_shm_proxy_init (commAtechE99MplShmProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = comm_atech_e99_mpl_shm_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, COMM_TYPE_ATECH_E99_MPL_SHM_PROXY, commAtechE99MplShmProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), comm_atech_e99_mpl_shm_interface_info ());
}

static void
comm_atech_e99_mpl_shm_proxy_class_init (commAtechE99MplShmProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = comm_atech_e99_mpl_shm_proxy_finalize;
  gobject_class->get_property = comm_atech_e99_mpl_shm_proxy_get_property;
  gobject_class->set_property = comm_atech_e99_mpl_shm_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = comm_atech_e99_mpl_shm_proxy_g_signal;
  proxy_class->g_properties_changed = comm_atech_e99_mpl_shm_proxy_g_properties_changed;

  comm_atech_e99_mpl_shm_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (commAtechE99MplShmProxyPrivate));
#endif
}

static void
comm_atech_e99_mpl_shm_proxy_iface_init (commAtechE99MplShmIface *iface)
{
  iface->get_verbose = comm_atech_e99_mpl_shm_proxy_get_verbose;
}

/**
 * comm_atech_e99_mpl_shm_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-atech-e99-mpl-shm.top_of_page">atech.e99.mpl.shm</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call comm_atech_e99_mpl_shm_proxy_new_finish() to get the result of the operation.
 *
 * See comm_atech_e99_mpl_shm_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
comm_atech_e99_mpl_shm_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (COMM_TYPE_ATECH_E99_MPL_SHM_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "atech.e99.mpl.shm", NULL);
}

/**
 * comm_atech_e99_mpl_shm_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to comm_atech_e99_mpl_shm_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with comm_atech_e99_mpl_shm_proxy_new().
 *
 * Returns: (transfer full) (type commAtechE99MplShmProxy): The constructed proxy object or %NULL if @error is set.
 */
commAtechE99MplShm *
comm_atech_e99_mpl_shm_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return COMM_ATECH_E99_MPL_SHM (ret);
  else
    return NULL;
}

/**
 * comm_atech_e99_mpl_shm_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-atech-e99-mpl-shm.top_of_page">atech.e99.mpl.shm</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See comm_atech_e99_mpl_shm_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type commAtechE99MplShmProxy): The constructed proxy object or %NULL if @error is set.
 */
commAtechE99MplShm *
comm_atech_e99_mpl_shm_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (COMM_TYPE_ATECH_E99_MPL_SHM_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "atech.e99.mpl.shm", NULL);
  if (ret != NULL)
    return COMM_ATECH_E99_MPL_SHM (ret);
  else
    return NULL;
}


/**
 * comm_atech_e99_mpl_shm_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like comm_atech_e99_mpl_shm_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call comm_atech_e99_mpl_shm_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See comm_atech_e99_mpl_shm_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
comm_atech_e99_mpl_shm_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (COMM_TYPE_ATECH_E99_MPL_SHM_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "atech.e99.mpl.shm", NULL);
}

/**
 * comm_atech_e99_mpl_shm_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to comm_atech_e99_mpl_shm_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with comm_atech_e99_mpl_shm_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type commAtechE99MplShmProxy): The constructed proxy object or %NULL if @error is set.
 */
commAtechE99MplShm *
comm_atech_e99_mpl_shm_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return COMM_ATECH_E99_MPL_SHM (ret);
  else
    return NULL;
}

/**
 * comm_atech_e99_mpl_shm_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like comm_atech_e99_mpl_shm_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See comm_atech_e99_mpl_shm_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type commAtechE99MplShmProxy): The constructed proxy object or %NULL if @error is set.
 */
commAtechE99MplShm *
comm_atech_e99_mpl_shm_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (COMM_TYPE_ATECH_E99_MPL_SHM_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "atech.e99.mpl.shm", NULL);
  if (ret != NULL)
    return COMM_ATECH_E99_MPL_SHM (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * commAtechE99MplShmSkeleton:
 *
 * The #commAtechE99MplShmSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * commAtechE99MplShmSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #commAtechE99MplShmSkeleton.
 */

struct _commAtechE99MplShmSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_comm_atech_e99_mpl_shm_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], COMM_TYPE_ATECH_E99_MPL_SHM);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, COMM_TYPE_ATECH_E99_MPL_SHM);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_comm_atech_e99_mpl_shm_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_comm_atech_e99_mpl_shm_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_comm_atech_e99_mpl_shm_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_comm_atech_e99_mpl_shm_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _comm_atech_e99_mpl_shm_skeleton_vtable =
{
  _comm_atech_e99_mpl_shm_skeleton_handle_method_call,
  _comm_atech_e99_mpl_shm_skeleton_handle_get_property,
  _comm_atech_e99_mpl_shm_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
comm_atech_e99_mpl_shm_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return comm_atech_e99_mpl_shm_interface_info ();
}

static GDBusInterfaceVTable *
comm_atech_e99_mpl_shm_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_comm_atech_e99_mpl_shm_skeleton_vtable;
}

static GVariant *
comm_atech_e99_mpl_shm_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_comm_atech_e99_mpl_shm_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _comm_atech_e99_mpl_shm_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _comm_atech_e99_mpl_shm_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _comm_atech_e99_mpl_shm_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "atech.e99.mpl.shm", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _comm_atech_e99_mpl_shm_emit_changed (gpointer user_data);

static void
comm_atech_e99_mpl_shm_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _comm_atech_e99_mpl_shm_emit_changed (skeleton);
}

static void
_comm_atech_e99_mpl_shm_on_signal_changes_notification (
    commAtechE99MplShm *object,
    gint arg_member_id,
    guint arg_change)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(iu)",
                   arg_member_id,
                   arg_change));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "atech.e99.mpl.shm", "ChangesNotification",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void comm_atech_e99_mpl_shm_skeleton_iface_init (commAtechE99MplShmIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (commAtechE99MplShmSkeleton, comm_atech_e99_mpl_shm_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (commAtechE99MplShmSkeleton)
                         G_IMPLEMENT_INTERFACE (COMM_TYPE_ATECH_E99_MPL_SHM, comm_atech_e99_mpl_shm_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (commAtechE99MplShmSkeleton, comm_atech_e99_mpl_shm_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (COMM_TYPE_ATECH_E99_MPL_SHM, comm_atech_e99_mpl_shm_skeleton_iface_init))

#endif
static void
comm_atech_e99_mpl_shm_skeleton_finalize (GObject *object)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (comm_atech_e99_mpl_shm_skeleton_parent_class)->finalize (object);
}

static void
comm_atech_e99_mpl_shm_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_comm_atech_e99_mpl_shm_emit_changed (gpointer user_data)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "atech.e99.mpl.shm",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_comm_atech_e99_mpl_shm_schedule_emit_changed (commAtechE99MplShmSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
comm_atech_e99_mpl_shm_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _comm_atech_e99_mpl_shm_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _comm_atech_e99_mpl_shm_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
comm_atech_e99_mpl_shm_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _comm_atech_e99_mpl_shm_schedule_emit_changed (skeleton, _comm_atech_e99_mpl_shm_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
comm_atech_e99_mpl_shm_skeleton_init (commAtechE99MplShmSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = comm_atech_e99_mpl_shm_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, COMM_TYPE_ATECH_E99_MPL_SHM_SKELETON, commAtechE99MplShmSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_BOOLEAN);
}

static gboolean 
comm_atech_e99_mpl_shm_skeleton_get_verbose (commAtechE99MplShm *object)
{
  commAtechE99MplShmSkeleton *skeleton = COMM_ATECH_E99_MPL_SHM_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
comm_atech_e99_mpl_shm_skeleton_class_init (commAtechE99MplShmSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = comm_atech_e99_mpl_shm_skeleton_finalize;
  gobject_class->get_property = comm_atech_e99_mpl_shm_skeleton_get_property;
  gobject_class->set_property = comm_atech_e99_mpl_shm_skeleton_set_property;
  gobject_class->notify       = comm_atech_e99_mpl_shm_skeleton_notify;


  comm_atech_e99_mpl_shm_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = comm_atech_e99_mpl_shm_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = comm_atech_e99_mpl_shm_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = comm_atech_e99_mpl_shm_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = comm_atech_e99_mpl_shm_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (commAtechE99MplShmSkeletonPrivate));
#endif
}

static void
comm_atech_e99_mpl_shm_skeleton_iface_init (commAtechE99MplShmIface *iface)
{
  iface->changes_notification = _comm_atech_e99_mpl_shm_on_signal_changes_notification;
  iface->get_verbose = comm_atech_e99_mpl_shm_skeleton_get_verbose;
}

/**
 * comm_atech_e99_mpl_shm_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-atech-e99-mpl-shm.top_of_page">atech.e99.mpl.shm</link>.
 *
 * Returns: (transfer full) (type commAtechE99MplShmSkeleton): The skeleton object.
 */
commAtechE99MplShm *
comm_atech_e99_mpl_shm_skeleton_new (void)
{
  return COMM_ATECH_E99_MPL_SHM (g_object_new (COMM_TYPE_ATECH_E99_MPL_SHM_SKELETON, NULL));
}

