/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp book.xml -i book.h -p bookInterface
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef BOOKINTERFACE_H
#define BOOKINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "person.h"
#include "message.h"
//#include "book.h"

/*
 * Proxy class for interface atech.e99.mpl
 */
class AtechE99MplInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "atech.e99.mpl"; }

public:
    AtechE99MplInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~AtechE99MplInterface();

    Q_PROPERTY(int person_removed READ person_removed)
    inline int person_removed() const
    { return qvariant_cast< int >(property("person_removed")); }

    Q_PROPERTY(int person_updated READ person_updated)
    inline int person_updated() const
    { return qvariant_cast< int >(property("person_updated")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> addPerson(const Person &person)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(person);
        return asyncCallWithArgumentList(QLatin1String("addPerson"), argumentList);
    }

    inline QDBusPendingReply<int> ipersonRemoved()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ipersonRemoved"), argumentList);
    }

    inline QDBusPendingReply<int> ipersonUpdated()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ipersonUpdated"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void messageSent(const message &msg);
    void personAdded(const Person &name);
    void personRemoved(const QString &name);
};

namespace atech {
  namespace e99 {
    typedef ::AtechE99MplInterface mpl;
  }
}
#endif
